### ISSUE TITLE
few feature request

### ISSUE THREAD

**Issue by madmax440** [COVESA/dlt-daemon#358]
Hello,

I would like to propose few feature requests.

1. split logs based on size - configurable option of log file in size to split when a particular size in KB reached.
2. log compression - when log file has been split, compress the older log file with gzip.

thanks,

**Comment by ssugiura** [comment]
@madmax440 
For first feature, we already have offline logstorage to store log outputs into file with specific amount and number.
Does this satisfy your request?
https://github.com/COVESA/dlt-daemon/blob/master/doc/dlt_offline_logstorage.md

**Comment by madmax440** [comment]
@ssugiura thanks, that solves the first feature. is there a way to compress dlt logs via configuration as well? or is this going to be a  new feature?

**Comment by ssugiura** [comment]
@madmax440 
That would definitely be a new feature.

**Comment by thanhbnq** [comment]
Hello @madmax440 ,

Thanks for your suggestion.
Your idea is completely a new feature so it would be really great if you already had your own implementation and contribute to community. In that case, please raise a PR for that.
Moreover, I would like to close this topic since you have no more discussion.

Thank you,
Thanh
