### ISSUE TITLE
How to receive DLT message on CANoe application with IPv6

### ISSUE THREAD

**Issue by phamcongspk** [COVESA/dlt-daemon#423]
Hello @thanhbnq 

I want to receive DLT message on CANoe application with IPv6 , but it do not work with both UDP and TCP
Related ticket has been created and closed here: https://github.com/COVESA/dlt-daemon/issues/419

In case of TCP: How can CANoe application receive DLT message like DLT-Viewer?
As I know, dlt-deamon play as a TCP server, so other clients (like DLT-Viewer) want to receive DLT message must to establish a connection with dlt-deamon. After that, DLT message will be transfer to client automatically. Is that right?

Regards,
Cong.

**Comment by thanhbnq** [comment]
Hello @phamcongspk ,

#419 is closed since based on our discussion and suggestion, the problem seems to be about networking configuration (IT stuff) not a DLT issue. Hence what we can support is to provide some hints to discuss with your IT dept. Thank you for understanding.

Regarding TCP connection, well, if your dlt-daemon can work with TCP, I would suggest to use dlt-viewer instead of CANoe application. It will be simpler than CANoe app.

I know CANoe application but I am not an expert. If you want to enhance CANoe app to work as dlt-viewer, you have to implement a part which connects to dlt-daemon via TCP socket (address and port). You also have to implement the part which decode the dlt messages received from dlt-daemon.  :) 

Happy coding !
Thanh

**Comment by thanhbnq** [comment]
Hello @phamcongspk ,

I'd like to close this discussion. I hope my answer is clear and helpful to your works.
In case you have any concerns or implementation, please (re-)open the discussion/ PRs, we are willing to discuss and incorporate.

Happy coding!
Thanh
