### ISSUE TITLE
Logging variations

### ISSUE THREAD

**Issue by vlajko96** [COVESA/dlt-daemon#426]
Is there a way I can select to write logs only in offline logstorage and not on ECU connected clients? Also is there a way I can select to write logs only in ECU connected clients and not in offline logstorage?

Best Regards

**Comment by minminlittleshrimp** [comment]
Hello,
Please clarify me if I am wrongly understanding your issue. For my understanding from your question, I have some information:

1.For offline logstorage: Yes, you just only set offlineLogstoragePath and offlineLogstorageCache. Then dlt logs will be kept in Flash mems (EMMCs, UFS, etc) waiting for your define Sync behavior (we design the sync behavior here due to limit of write cycles for Flash mems) to sync logs onto the path you set. Here dlt-daemon ring buffer will be used.

2.For ECU only: Yes, you could unset offlineLogstorageCache value. Then triggers the storing process by sending control message from dlt-logstorage-ctrl. Now each filter has its own buffer and will be used for buffering logs onto specific ECU.

Hello @michael-methner 
Please kindly review on this issue and correct me if there is incorrect info I state here.

Regards
