### ISSUE TITLE
storage loglevel is not update using dlt-control

### ISSUE THREAD

**Issue by ghost** [COVESA/dlt-daemon#576]
I want to be able to change storage loglevel using dlt-control so that it is possible to both increase and decrease the storage loglevel.
As of now I doesn't seems to change at all only context->loglevel for which I suspect is used in the online logs.

**Comment by minminlittleshrimp** [comment]
Hello @drdevil080 
thanks for your dropping report here.

I have checked and it seems that everything is fine for changing logs with dlt-control.
I am not so sure about changing log level within logstorage, do you mean changing the log level in FILTER. If that is what you want to mention, I would say that you cannot do that, due to the current implementation, all filters will be parsed into internal Data structure and not receive any runtime values after that.

Please clarify for me your case in detail.
Thank you

**Comment by drdevil080** [comment]
Hello!
That is correct, I want to be able to change the log level that is used for writing to the offline logs, meaning the dlt file. Thank you for verifying this is the case, this is something that is really important for us and I am trying to modify the code to make this works. Do you have any proposal how to proceed? I am currently trying to the following changes:
diff --git a/src/daemon/dlt_daemon_common.c b/src/daemon/dlt_daemon_common.c
index 6ba5935..2edf41c 100644
--- a/src/daemon/dlt_daemon_common.c
+++ b/src/daemon/dlt_daemon_common.c
@@ -1361,9 +1361,13 @@ int dlt_daemon_user_send_log_level(DltDaemon *daemon, DltDaemonContext *context,
         (daemon->maintain_logstorage_loglevel != DLT_MAINTAIN_LOGSTORAGE_LOGLEVEL_OFF))
             usercontext.log_level = (uint8_t) (context->log_level >
                 context->storage_log_level ? context->log_level : context->storage_log_level);
-    else /* Storage log level is not updated (is DEFAULT) then  no device is yet connected so ignore */
+    else
+    {   /* Storage log level is not updated (is DEFAULT) then  no device is yet connected so ignore */
         usercontext.log_level =
             (uint8_t) ((context->log_level == DLT_LOG_DEFAULT) ? daemon->default_log_level : context->log_level);
+        dlt_vlog(LOG_WARNING, "%s: Will change logstorage loglevel to %d\n", __func__, context->log_level);
+       context->storage_log_level = context->log_level;
+    }

and then when writing to file I am looking into how to get the new storage_loglevel and not the one that is used from the filter:

diff --git a/src/offlinelogstorage/dlt_offline_logstorage.c b/src/offlinelogstorage/dlt_offline_logstorage.c
index a03a861..056f8bf 100644
--- a/src/offlinelogstorage/dlt_offline_logstorage.c
+++ b/src/offlinelogstorage/dlt_offline_logstorage.c
@@ -2081,6 +2081,15 @@ DLT_STATIC int dlt_logstorage_filter(DltLogStorage *handle,
             continue;

         /* filter on log level */
+        dlt_vlog(LOG_WARNING, "config[i]->log_level = %d - log_level = log_level %d\n", config[i]->log_level, log_level);
+        if (handle->config_list[i].data->log_level != NULL)
+        {
+            dlt_vlog(LOG_WARNING, "handle->config_list[i].data->log_level = %d\n", handle->config_list[i].data->log_level);
+        }
+        else
+        {
+            dlt_log(LOG_DEBUG, "handle->config_list[i].data->log_level is null for some reason \n");
+        }
         if (log_level > config[i]->log_level) {
             config[i] = NULL;
             continue;


Appreciate your assistance and quick response 😄

Kind regards Daniel
________________________________
Från: Minh Quang Luu ***@***.***>
Skickat: den 29 november 2023 10:21
Till: COVESA/dlt-daemon ***@***.***>
Kopia: drdevil080 ***@***.***>; Mention ***@***.***>
Ämne: Re: [COVESA/dlt-daemon] storage loglevel is not update using dlt-control (Issue #576)


Hello @drdevil080<https://github.com/drdevil080>
thanks for your dropping report here.

I have checked and it seems that everything is fine for changing logs with dlt-control.
I am not so sure about changing log level within logstorage, do you mean changing the log level in FILTER. If that is what you want to mention, I would say that you cannot do that, due to the current implementation, all filters will be parsed into internal Data structure and not receive any runtime values after that.

Please clarify for me your case in detail.
Thank you

**Comment by Bichdao021195** [comment]
Hi Minh

**Comment by minminlittleshrimp** [comment]
Hello @drdevil080 
Could you kindly provide us:
```
+ Test steps
+ dlt.conf
+ dlt_logstorage.conf
```
We need more info to reproduce this issue.
Thank you in advance.

**Comment by Bichdao021195** [comment]
Hi @drdevil080 
Which use case do you want to change logstorage log level via dlt-control?
Why is it important for you?
Thank you in advance.

**Comment by Bichdao021195** [comment]
Hi @drdevil080 
You can change dlt_logstorage.conf and then re run dlt-logstorage-ctrl. In this time, dlt-daemon will reload the dlt_logstorage.conf and you can change the storage log level. The below is my example. I hope that this way is helpful for you. 

**Step1:** Update dlt_logstorage.conf with log level that you want to change
'''
[General]
MaintainLogstorageLogLevel=OFF
[FILTER1]
LogAppName=LOG
ContextName=TEST
LogLevel=DLT_LOG_ERROR
File=test
FileSize=50000
NOFiles=5
'''

**Step2**: Re run dlt-logstorage-ctrl
dlt-logstorage-ctrl -c 1 -p /var/dltlogs/

**Step 3**: Monitor that dlt-daemon upload the dlt_logstorage.conf or not. The dlt-daemon log will show log as below if reload dlt_logstorage successfully.

43821.083826]~DLT~232944~WARNING  ~Entry does not exist in section: ExcludedLogAppName
[43821.083829]~DLT~232944~WARNING  ~Entry does not exist in section: ExcludedContextName
[43821.083832]~DLT~232944~WARNING  ~Entry does not exist in section: SyncBehavior
[43821.083842]~DLT~232944~WARNING  ~Entry does not exist in section: OverwriteBehavior
[43821.083843]~DLT~232944~WARNING  ~Entry does not exist in section: EcuID
[43821.083844]~DLT~232944~WARNING  ~Entry does not exist in section: SpecificSize
[43821.083854]~DLT~232944~WARNING  ~Entry does not exist in section: GzipCompression


**Step4:** Use cmd "watch -n 1 ls -al" to check the storage log. 

Best Reagards,
Dao Nguyen

**Comment by minminlittleshrimp** [comment]
Closed due to the request violating Autosar standard.
Also, the reporter's account is removed.
