### ISSUE TITLE
Not able to control dlt logs using the dlt-control

### ISSUE THREAD

**Issue by MAZEEM2** [COVESA/dlt-daemon#680]
I am running the dlt-control command but not be able to control the Android logs that has been converted into DLT format.
->> command --> dlt-control -e ANDR -a LOGD -l 0 localhost

logs which i have captured at the boot time of dlt-daemon is [Uploading dlt_boot_logs.txt…]()

if you analyse these logs you'll find 
 1.[    4.463744]~DLT~  739~ERROR    ~/dev/socket/dlt[    4.463746]~DLT~  739~ERROR    ~dlt
 2.[    4.463889]~DLT~  739~ERROR    ~/data/dlt-ctrl.sock[    4.463891]~DLT~  739~ERROR    ~dlt-ctrl.sock
 3.Cannot open configuration file: /data/dlt-runtime.cfg
 4.dlt_daemon_applications_load: cannot open file /data/dlt-runtime-application.cfg: No such file or directory
 
 https://github.com/MAZEEM2

**Comment by minminlittleshrimp** [comment]
Sorry the log file seems wrongly attached.
The issue is with the socket creating process when doing init phase in vendor (I assume dlt will be placed in /vendor in your aosp rfs). You have 2 solutions, either you config dlt sock in /dev/socket as an android way, or use a custom sock path.

The funiest thing is that socket creating using rc file is trying to custom with /data, whether Android.bp with /dev/socket

https://github.com/COVESA/dlt-daemon/blob/1533d0fc8e9ec0d90f1d675c2bca416f463ff71a/src/daemon/dlt-daemon.rc#L10

https://github.com/COVESA/dlt-daemon/blob/1533d0fc8e9ec0d90f1d675c2bca416f463ff71a/Android.bp#L32

Before patchset/PR applied, please try one out of two, custom: replace dev/socket with data/dlt (dont remember please check the rc file), /dev/socket: android way so I believe via type enforcement file (SEpolicy)

Regards

**Comment by MAZEEM2** [comment]
I want to with the latest dlt-daemon 2.18.10 will i be able to control the log level of converted logd logs into dlt logs.

OR

@minminlittleshrimp  Can you explain me If i have to control the loglevel  of logd logs that is getting converted into the dlt. 
for doing this what n all things required or what n all binaries required or what n all points that i have to consider to make it working in the latest dlt-daemon

**Comment by MAZEEM2** [comment]
Hello @minminlittleshrimp  . can you please help in this
